---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
pages:
- _elevators/1111.md
- _projects/1149.md
- _projects/9526.md
